### ISSUE TITLE
Misleading 422 data integrity error

### ISSUE THREAD

**Issue by hongbo-miao** [ProsperWorks/copper-sdk#9]
I am using [Create a New Lead API](https://developer.copper.com/?version=latest#c99527d7-4c60-473e-badb-4a70aca14e21).

This issue is not specific for copper-sdk, you can use Postman to test this:

The request body is
```json
{
  "first_name": "a",
  "last_name": "b",
  "email": {
    "email":"c@c.c",
    "category":"work"
  }
}
```

It works before.

However, since this week, I got this error
```json
{
    "success": false,
    "status": 422,
    "message": "Data integrity error"
}
```

I thought I did something wrong or the API changed in the beginning. I turns out if I change to other email address, it works again.

I am guessing I always use `c@c.c` to test, it got blocked by Copper (?)

The current error is kind of misleading. It will be great to improve the error code and message.

**Comment by guangda-prosperworks** [comment]
@Hongbo-Miao Thanks for filing this issue. I'll transfer the issue to our API team.

**Comment by Rroshan12** [comment]
Our app is voip app we are integrating our app..while integrating we find some problem in copper-sdk library
in this part
sdk.on('phoneNumberClicked', function ({ number }) {
// do something with number
})

cant pass number params please defined number params in sdk on interface
while function number params is passed in doc but in sdk there is not any params!

**Comment by apellerano-pw** [comment]
This issue has been addressed at some point. I'm able to create multiple leads with the given request body.
